import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'di.config.dart';

/// Global service locator.
final GetIt getIt = GetIt.instance;

/// Initialize the DI container (generated by Injectable).
@InjectableInit()
void configureDependencies() {
  getIt.init();
}
